
# List of test categories to include in the run.
# Valid values: unit, integration, e2e, cli, perf
enabled_scope:
  # web, api, smoke, full, unit, integration, e2e
  - web
  - smoke

engine:
  project_id: "callook-automation-demo"
  test_root: "test/integration"
  prometheus: false
  logging: true


# Output settings for reporting tools
reporting:
  allure_enabled: true
  allure_service: "http://localhost:5050"
  include_timestamps: true
  output_dir: "output/"

# Reserved for future: performance monitoring, AI analysis, etc.
features:
  performance_tracking: false
  ai_flake_classification: false